[PHP]
engine = On
precision = 14
output_buffering = 4096
zlib.output_compression = Off
implicit_flush = Off
serialize_precision = -1
zend.enable_gc = On
expose_php = Off
max_execution_time = 60
max_input_time = 60
max_input_vars = 10000
memory_limit = -1
error_reporting = -1
display_errors = Off
display_startup_errors = Off
log_errors = On
log_errors_max_len = 0
error_log = /proc/self/fd/2
ignore_repeated_errors = Off
ignore_repeated_source = Off
report_memleaks = On
html_errors = On
variables_order = "GPCS"
request_order = "GP"
register_argc_argv = Off
auto_globals_jit = On
post_max_size = 40M
default_mimetype = "text/html"
default_charset = "UTF-8"
enable_dl = Off
file_uploads = On
upload_max_filesize = 38M
max_file_uploads = 20
allow_url_fopen = On
allow_url_include = Off
default_socket_timeout = 60
zend.assertions = 1
assert.exception = 1

[CLI Server]
cli_server.color = On

[Date]
; Спека: время хранится и считается в UTC, локаль — забота клиента.
date.timezone = "UTC"

[PostgreSQL]
pgsql.allow_persistent = On
pgsql.auto_reset_persistent = Off
pgsql.max_persistent = -1
pgsql.max_links = -1
pgsql.ignore_notice = 0
pgsql.log_notice = 0

[Session]
session.save_handler = files
session.use_strict_mode = 1
session.use_cookies = 1
session.use_only_cookies = 1
session.name = PHPSESSID
session.auto_start = 0
session.cookie_lifetime = 0
session.cookie_path = /
session.cookie_httponly = 1
session.serialize_handler = php
session.gc_probability = 1
session.gc_divisor = 100
session.gc_maxlifetime = 60
session.cache_limiter = nocache
session.cache_expire = 180
session.use_trans_sid = 0

[opcache]
opcache.save_comments = 1
opcache.enable = 1
opcache.enable_cli = 1

[apcu]
apc.enable_cli = On

[xdebug]
xdebug.mode = coverage
xdebug.show_exception_trace = 0